# Generated by Django 3.1 on 2020-10-08 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20201008_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='articletag',
            name='main',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
